### ISSUE TITLE
move-unit-test failures

### ISSUE THREAD

**Issue by ksolana** [anza-xyz/sui#15]
$ cargo test --manifest-path external-crates/move/Cargo.toml --features solana-backend -p move-unit-test -- --test-threads=1

failures:
    run_test::address_args.move
    run_test::arithmetic_errors.move
    run_test::construct_data.move
    run_test::cross_module_aborts.move
    run_test::do_nothing.move
    run_test::expected_abort_no_abort.move
    run_test::native_abort.move
    run_test::non_exsistent_native.move
    run_test::other_expected_failures.move
    run_test::out_of_gas.move
    run_test::proposal_test.move
    run_test::signer_args.move
    run_test::timeout.move
    run_test::unexpected_abort.move
    run_test::use_unit_test_module.move

**Comment by ksolana** [comment]
```
test run_test::address_args.move            ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
FAILED
test run_test::arithmetic_errors.move       ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::construct_data.move          ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::cross_module_aborts.move     ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::do_nothing.move              ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::expected_abort_no_abort.move ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::native_abort.move            ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::non_exsistent_native.move    ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::other_expected_failures.move ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::out_of_gas.move              ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::proposal_test.move           ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::signer_args.move             ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::timeout.move                 ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::unexpected_abort.move        ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED
test run_test::use_unit_test_module.move    ... thread '<unnamed>' panicked at solana/move-to-solana/src/lib.rs:142:52:
move native: NotPresent
FAILED

```

**Comment by ksolana** [comment]
oh nvm. i needed to export MOVE_NATIVE.
